apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: maintenance-page
    files:
      - index.html
      - logo.png
    options:
      disableNameSuffixHash: true  # Nombre estable para montarlo en el deployment
