apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-principal
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - mi-nas-vaz.myqnapcloud.com
        - sistema.mycloudnas.com
      secretName: wildcard-mydominio-tls  # Lo rellena cert-manager (Let's Encrypt)
  rules:
    - host: mi-nas-vaz.myqnapcloud.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indumentaria-service
                port:
                  number: 80
    - host: sistema.mycloudnas.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: saas-service
                port:
                  number: 80
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: indumentaria-service
                port:
                  number: 80
